store a user's keys to a database(task 16)
TSELab/SBOMCtl pull request #6
Opened 2024-10-21 21:41 UTC by chinenyeokafor

### Purpose
This pull request implements task 16(store a user's key to a database)

2024-10-22 20:48 UTC, abuishgair requested changes

2024-10-22 20:48 UTC, abuishgair commented on privateSBOMExchange/src/scripts/key_db.py
keys are already generated and saved in a file, please assume you have file path

2024-10-22 20:48 UTC, abuishgair commented on privateSBOMExchange/src/scripts/key_gen.py
please take  in consideration that keys are already generated and stored In file

2024-10-24 02:38 UTC, closed without merging

2024-10-24 03:00 UTC, chinenyeokafor commented
#9 updates this